name: Aktywnosc
main: me.gacekmpl2.craftmpg.Main
authors: [GacekMPL2, Pijok, mkko120]
version: 1.0
commands:
  aktywnosc:
    usage: /aktywnosc
  timelog:
    usage: /timelog
    aliases: [timelogs, logi, timelogi]